from operator import add
from typing import Annotated, Literal

from pydantic import BaseModel, Field


class AgentSchema(BaseModel):
    messages: Annotated[list, add] = (
        (Field(..., description="List of messages exchanged with the agent"),),
    )
    user_question: str = (
        Field(..., description="The original question asked by the user"),
    )
    curated_question: str = (Field(..., description="Curated question for the agent"),)
    prompt_query_context: str = (
        (
            Field(
                ...,
                description="A detailed prompt with SQL DB context that will help the agent to generate the SQL query",
            ),
        ),
    )
    is_safe: Literal["Yes", "No"] = (
        Field(
            ..., description="Indicates if the generated SQL query is safe to execute"
        ),
    )
    generated_sql_query: str = (
        Field(..., description="The SQL query generated by the agent"),
    )
    sql_query_execution_result: str = (
        Field(..., description="The result of executing the generated SQL query"),
    )
    final_answer: str = Field(
        ...,
        description="The final answer provided by the agent after processing the SQL query result",
    )
