"""LangGraph state schemas shared across the project's agents.

Each class below is a Pydantic model that defines the "state" object a
LangGraph graph passes between its nodes. Every node function receives one
of these objects, reads whatever fields it needs, updates the relevant
fields, and returns the (same type of) object for the next node.

Fields typed as ``Annotated[list, add]`` use LangGraph's reducer pattern:
instead of overwriting the list on every update, LangGraph appends
("adds") new items to the existing list. This is how the running
conversation history (``messages``) is built up as the graph executes.
"""

from operator import add
from typing import Annotated, Literal

from pydantic import BaseModel, Field


class AgentSchema(BaseModel):
    """Schema for the SQL Agent state.

    This is the state object that flows through every node of the
    ``sql_analyst`` graph (see ``agents/sql_analyst.py``), from curating
    the user's question all the way to presenting the final answer.
    """

    messages: Annotated[list, add] = Field(
        default_factory=list, description="List of messages exchanged with the agent"
    )

    user_question: str = Field(
        default="", description="The original question asked by the user"
    )

    curated_question: str = Field(
        default="", description="Curated question for the agent"
    )

    prompt_query_context: str = Field(
        default="",
        description="A detailed prompt with SQL DB context that will help the agent to generate the SQL query",
    )

    is_safe: Literal["yes", "no"] = Field(
        default="no",
        description="Indicates if the generated SQL query is safe to execute",
    )

    comments: str = Field(
        default="",
        description="Comments regarding the safety of the generated SQL query",
    )

    generated_sql_query: str = Field(
        default="", description="The SQL query generated by the agent"
    )

    sql_query_execution_result: str = Field(
        default="", description="The result of executing the generated SQL query"
    )

    final_answer: str = Field(
        default="",
        description="The final answer provided by the agent after processing the SQL query result",
    )


class JudgeAgentSchema(BaseModel):
    """Schema for the SQL Judge agent.

    Used as the structured-output schema for the "is this SQL query safe"
    check inside ``sql_analyst.py`` (``is_safe_sql`` node). The LLM is
    forced to answer in exactly this shape so the graph can branch on
    ``answer`` programmatically instead of parsing free-form text.
    """

    answer: Literal["yes", "no"] = Field(
        description="Return 'yes' if the SQL query ONLY retrieves data (like SELECT). Return 'no' if it modifies data (like INSERT, UPDATE, DELETE, DROP)."
    )

    comments: str = Field(
        default="",
        description="Comments or feedback from the judge agent regarding the SQL query",
    )


class ETLAgentSchema(BaseModel):
    """ReAct Mode: Schema for the SQL ETL agent.

    Deliberately minimal (just a running message list) because the
    ``etl_analyst`` graph follows the classic ReAct loop: the LLM decides
    which tool to call by looking at ``messages``, the tool result is
    appended back onto ``messages``, and the loop repeats until the LLM
    stops requesting tools.
    """

    messages: Annotated[list, add] = Field(
        default_factory=list,
        description="List of messages to be processed by the ETL agent",
    )


class RouterSchema(BaseModel):
    """Structured-output schema for the top-level router node.

    ``data_agent.py`` forces the routing LLM to answer with this schema so
    the graph can send the request straight to "sql_node" or "etl_node"
    without having to parse a free-text reply.
    """

    answer: Literal["sql", "etl"] = Field(
        default="sql",
        description="Indicates whether the user's question is related to SQL or ETL operations",
    )
    comments: str = Field(
        default="",
        description="Additional comments or feedback regarding the classification of the user's question",
    )


class DataAgentSchema(BaseModel):
    """State for the top-level ``data_agent`` graph.

    This is the outermost state object: it only tracks the conversation
    (``messages``) and the routing decision (``route_response``). The
    heavier, agent-specific state (``AgentSchema`` / ``ETLAgentSchema``) is
    created fresh inside the SQL/ETL sub-graphs and never leaks back up
    here — only their final response message does.
    """

    messages: Annotated[list, add] = Field(
        default_factory=list,
        description="List of messages to be processed by the Data agent",
    )
    route_response: str = Field(
        default="",
        description="The response from the router indicating whether to route to SQL or ETL operations",
    )
